name: meta-bert
channels:
  - defaults
dependencies:
  - pip=21.2.2
  - python=3.8.0
  - pip:
    - numpy==1.21.2
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - tokenizers==0.10.3
    - torch==1.9.0
    - torchvision==0.10.0
    - tqdm==4.62.2
    - transformers==4.10.2
